name: pdf_pseudo_env
dependencies:
  - python=3.10
  - pip:
    - anonymeter = 0.0.2
    - anonymize = 0.5
    - anonymizer==0.0.6
    - asttokens==2.2.1
    - attrs==23.1.0
    - backcall==0.2.0
    - cape-dataframes==0.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - comm==0.1.4
    - contourpy==1.1.0
    - cycler==0.11.0
    - DateTime==5.2
    - debugpy==1.6.7.post1
    - decorator==5.1.1
    - executing==1.2.0
    - fastjsonschema==2.18.0
    - fonttools==4.42.1
    - idna==3.4
    - ipykernel==6.25.1
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - jedi==0.19.0
    - joblib==1.3.2
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter_client==8.3.0
    - jupyter_core==5.3.1
    - kiwisolver==1.4.4
    - kmodes==0.12.2
    - llvmlite==0.40.1
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - nbformat==5.9.2
    - nest-asyncio==1.5.7
    - numba==0.57.1
    - numpy==1.23.5
    - packaging==23.1
    - pandas==1.5.3
    - parso==0.8.3
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==10.0.0
    - platformdirs==3.10.0
    - plotly==5.16.1
    - prompt-toolkit==3.0.39
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9.7
    - pycanon==1.0.1.post1
    - pycryptodome==3.18.0
    - Pygments==2.16.1
    - pyparsing==3.0.9
    - pyspark==3.4.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    - PyYAML==6.0.1
    - pyzmq==25.1.1
    - referencing==0.30.2
    - requests==2.31.0
    - rfc3339==6.2
    - rpds-py==0.9.2
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - seaborn==0.12.2
    - six==1.16.0
    - sklearn==0.0.post7
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - tabulate==0.9.0
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - tornado==6.3.3
    - traitlets==5.9.0
    - typer==0.9.0
    - typing_extensions==4.7.1
    - tzdata==2023.3
    - urllib3==2.0.4
    - validators==0.21.2
    - wcwidth==0.2.6
    - zope.interface==6.0
